name: 📰 Haber Ekle
description: Siteye kendi haberini/konunu ekle
title: "[Haber] "
labels: ["haber"]
body:
  - type: input
    id: baslik
    attributes:
      label: Başlık
    validations:
      required: true
  - type: dropdown
    id: kategori
    attributes:
      label: Kategori
      options: [teknoloji, gundem]
    validations:
      required: true
  - type: textarea
    id: aciklama
    attributes:
      label: Açıklama
      description: Haberin kısa metni (isteğe bağlı)
  - type: textarea
    id: resim
    attributes:
      label: Resim
      description: Resmi buraya sürükle-bırak yap ya da resim linkini yapıştır
  - type: input
    id: link
    attributes:
      label: Link
      description: Haberin kaynağı / devamı (isteğe bağlı)
      placeholder: https://
  - type: checkboxes
    id: secenek
    attributes:
      label: Seçenekler
      options:
        - label: Sabitle (en üstte büyük göster)
